"""Library applying PNFL league rules and validation to a Front Page Sports Football Pro '98 coaching profile (.prf)."""

from fbpro98_profile import (
    DEFENSE_DISPLAY_CATEGORIES,
    OFFENSE_DISPLAY_CATEGORIES,
    CategoryWeights,
    Down,
    FieldPosition,
    InvalidProfileError,
    MinutesRemaining,
    PatMinutesRemaining,
    PatPointSpread,
    PatSituation,
    PointSpread,
    Profile,
    ProfileType,
    Situation,
    SubstitutionPair,
    SubstitutionSettings,
    UnsupportedProfileError,
    YardsToGo,
    build_profile_bytes,
    parse_profile,
    read_profile,
    write_profile,
)

from pnfl_profile.model import (
    PnflProfile,
    PnflRuleWarning,
    RuleName,
    Violation,
)
from pnfl_profile.rules import (
    DEFENSE_CATEGORIES,
    OFFENSE_CATEGORIES,
    PASS_LONG_ANY,
    PASS_MEDIUM_ANY,
    PASS_SHORT_ANY,
    PNFL_RULES,
    PnflRules,
    SituationKey,
    SituationRule,
)
from pnfl_profile.validators import validate_profile

__all__ = [
    "DEFENSE_CATEGORIES",
    "DEFENSE_DISPLAY_CATEGORIES",
    "OFFENSE_CATEGORIES",
    "OFFENSE_DISPLAY_CATEGORIES",
    "PASS_LONG_ANY",
    "PASS_MEDIUM_ANY",
    "PASS_SHORT_ANY",
    "PNFL_RULES",
    "CategoryWeights",
    "Down",
    "FieldPosition",
    "InvalidProfileError",
    "MinutesRemaining",
    "PatMinutesRemaining",
    "PatPointSpread",
    "PatSituation",
    "PnflProfile",
    "PnflRuleWarning",
    "PnflRules",
    "PointSpread",
    "Profile",
    "ProfileType",
    "RuleName",
    "Situation",
    "SituationKey",
    "SituationRule",
    "SubstitutionPair",
    "SubstitutionSettings",
    "UnsupportedProfileError",
    "Violation",
    "YardsToGo",
    "build_profile_bytes",
    "parse_profile",
    "read_profile",
    "validate_profile",
    "write_profile",
]
